base_link_size: 0.158 0.158 0.053 
platform_size: 0.12 0.12 0.065
arm1_size:
    - 0.135
    - 0.04
arm2_size:
    - 0.162
    - 0.03
gripper_size: 0.06 0.03 0.06
platform_origins: 0 0 0.0325
arm1_origins: 0 0 0.0675
arm2_origins: 0 0 0.081
gripper_origins: 
    - 0.03 0 0
    - 0 1.571 0
fourth_size: 0.06 0.06 0.05
fourth_origins: 0.0 0.0 0.025
joint1_limits:
    - -1.571
    - 1.571
joint1_velocity: 
    - 320.0
joint1_axis: 0 0 1
effort: 100
joint2_limits:
    - 0.0
    - 1.571
joint2_velocity: 
    - 320.0
joint2_axis: 0 1 0
joint3_limits:
    - 0.5
    - 1.571
joint3_velocity: 
    - 320.0
joint3_axis: 0 1 0
joint4_limits:
    - -1.571
    - 1.571
joint4_velocity: 
    - 480.0
joint5_limits:
    - -1.571
    - 1.571
joint5_axis: 0 1 0
joint5_origins: 0.0 0.0 0.162
joint4_axis: 1 0 0
joint1_origins: 0 0 0.02515
joint2_origins: 0 0 0.065
joint3_origins: 0 0 0.135
joint4_origins: 0.03 0.0 0.025
