// Generated by gencpp from file dobot/GetDeviceVersionResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETDEVICEVERSIONRESPONSE_H
#define DOBOT_MESSAGE_GETDEVICEVERSIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GetDeviceVersionResponse_
{
  typedef GetDeviceVersionResponse_<ContainerAllocator> Type;

  GetDeviceVersionResponse_()
    : result(0)
    , majorVersion(0)
    , minorVersion(0)
    , revision(0)  {
    }
  GetDeviceVersionResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , majorVersion(0)
    , minorVersion(0)
    , revision(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef uint8_t _majorVersion_type;
  _majorVersion_type majorVersion;

   typedef uint8_t _minorVersion_type;
  _minorVersion_type minorVersion;

   typedef uint8_t _revision_type;
  _revision_type revision;





  typedef boost::shared_ptr< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDeviceVersionResponse_

typedef ::dobot::GetDeviceVersionResponse_<std::allocator<void> > GetDeviceVersionResponse;

typedef boost::shared_ptr< ::dobot::GetDeviceVersionResponse > GetDeviceVersionResponsePtr;
typedef boost::shared_ptr< ::dobot::GetDeviceVersionResponse const> GetDeviceVersionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GetDeviceVersionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot::GetDeviceVersionResponse_<ContainerAllocator1> & lhs, const ::dobot::GetDeviceVersionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.majorVersion == rhs.majorVersion &&
    lhs.minorVersion == rhs.minorVersion &&
    lhs.revision == rhs.revision;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot::GetDeviceVersionResponse_<ContainerAllocator1> & lhs, const ::dobot::GetDeviceVersionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3c3f825efd26e7d40dd5c75956d6244";
  }

  static const char* value(const ::dobot::GetDeviceVersionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3c3f825efd26e7dULL;
  static const uint64_t static_value2 = 0x40dd5c75956d6244ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GetDeviceVersionResponse";
  }

  static const char* value(const ::dobot::GetDeviceVersionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"uint8 majorVersion\n"
"uint8 minorVersion\n"
"uint8 revision\n"
"\n"
;
  }

  static const char* value(const ::dobot::GetDeviceVersionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.majorVersion);
      stream.next(m.minorVersion);
      stream.next(m.revision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDeviceVersionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GetDeviceVersionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GetDeviceVersionResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "majorVersion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.majorVersion);
    s << indent << "minorVersion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.minorVersion);
    s << indent << "revision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.revision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GETDEVICEVERSIONRESPONSE_H
