// Generated by gencpp from file dobot/GetEndEffectorLaserResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETENDEFFECTORLASERRESPONSE_H
#define DOBOT_MESSAGE_GETENDEFFECTORLASERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GetEndEffectorLaserResponse_
{
  typedef GetEndEffectorLaserResponse_<ContainerAllocator> Type;

  GetEndEffectorLaserResponse_()
    : result(0)
    , enableCtrl(0)
    , on(0)  {
    }
  GetEndEffectorLaserResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , enableCtrl(0)
    , on(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef uint8_t _enableCtrl_type;
  _enableCtrl_type enableCtrl;

   typedef uint8_t _on_type;
  _on_type on;





  typedef boost::shared_ptr< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetEndEffectorLaserResponse_

typedef ::dobot::GetEndEffectorLaserResponse_<std::allocator<void> > GetEndEffectorLaserResponse;

typedef boost::shared_ptr< ::dobot::GetEndEffectorLaserResponse > GetEndEffectorLaserResponsePtr;
typedef boost::shared_ptr< ::dobot::GetEndEffectorLaserResponse const> GetEndEffectorLaserResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator1> & lhs, const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.enableCtrl == rhs.enableCtrl &&
    lhs.on == rhs.on;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator1> & lhs, const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8f296ec06b91031fd6d56c18b2ea1e9";
  }

  static const char* value(const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8f296ec06b91031ULL;
  static const uint64_t static_value2 = 0xfd6d56c18b2ea1e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GetEndEffectorLaserResponse";
  }

  static const char* value(const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"uint8 enableCtrl\n"
"uint8 on\n"
"\n"
;
  }

  static const char* value(const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.enableCtrl);
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEndEffectorLaserResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GetEndEffectorLaserResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "enableCtrl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableCtrl);
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GETENDEFFECTORLASERRESPONSE_H
