// Generated by gencpp from file dobot/GetIOPWMRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETIOPWMREQUEST_H
#define DOBOT_MESSAGE_GETIOPWMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GetIOPWMRequest_
{
  typedef GetIOPWMRequest_<ContainerAllocator> Type;

  GetIOPWMRequest_()
    : address(0)  {
    }
  GetIOPWMRequest_(const ContainerAllocator& _alloc)
    : address(0)  {
  (void)_alloc;
    }



   typedef uint8_t _address_type;
  _address_type address;





  typedef boost::shared_ptr< ::dobot::GetIOPWMRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GetIOPWMRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetIOPWMRequest_

typedef ::dobot::GetIOPWMRequest_<std::allocator<void> > GetIOPWMRequest;

typedef boost::shared_ptr< ::dobot::GetIOPWMRequest > GetIOPWMRequestPtr;
typedef boost::shared_ptr< ::dobot::GetIOPWMRequest const> GetIOPWMRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GetIOPWMRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GetIOPWMRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot::GetIOPWMRequest_<ContainerAllocator1> & lhs, const ::dobot::GetIOPWMRequest_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot::GetIOPWMRequest_<ContainerAllocator1> & lhs, const ::dobot::GetIOPWMRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetIOPWMRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetIOPWMRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetIOPWMRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetIOPWMRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetIOPWMRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetIOPWMRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GetIOPWMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "972132462544b1029bf37f19a88e11c4";
  }

  static const char* value(const ::dobot::GetIOPWMRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x972132462544b102ULL;
  static const uint64_t static_value2 = 0x9bf37f19a88e11c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GetIOPWMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GetIOPWMRequest";
  }

  static const char* value(const ::dobot::GetIOPWMRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GetIOPWMRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 address\n"
;
  }

  static const char* value(const ::dobot::GetIOPWMRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GetIOPWMRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIOPWMRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GetIOPWMRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GetIOPWMRequest_<ContainerAllocator>& v)
  {
    s << indent << "address: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.address);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GETIOPWMREQUEST_H
