// Generated by gencpp from file dobot/SetHOMECmdRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETHOMECMDREQUEST_H
#define DOBOT_MESSAGE_SETHOMECMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct SetHOMECmdRequest_
{
  typedef SetHOMECmdRequest_<ContainerAllocator> Type;

  SetHOMECmdRequest_()
    : isQueued(false)  {
    }
  SetHOMECmdRequest_(const ContainerAllocator& _alloc)
    : isQueued(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isQueued_type;
  _isQueued_type isQueued;





  typedef boost::shared_ptr< ::dobot::SetHOMECmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::SetHOMECmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHOMECmdRequest_

typedef ::dobot::SetHOMECmdRequest_<std::allocator<void> > SetHOMECmdRequest;

typedef boost::shared_ptr< ::dobot::SetHOMECmdRequest > SetHOMECmdRequestPtr;
typedef boost::shared_ptr< ::dobot::SetHOMECmdRequest const> SetHOMECmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::SetHOMECmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot::SetHOMECmdRequest_<ContainerAllocator1> & lhs, const ::dobot::SetHOMECmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.isQueued == rhs.isQueued;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot::SetHOMECmdRequest_<ContainerAllocator1> & lhs, const ::dobot::SetHOMECmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetHOMECmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetHOMECmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetHOMECmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0123d3476f07c7f6516fa3b297a41a96";
  }

  static const char* value(const ::dobot::SetHOMECmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0123d3476f07c7f6ULL;
  static const uint64_t static_value2 = 0x516fa3b297a41a96ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/SetHOMECmdRequest";
  }

  static const char* value(const ::dobot::SetHOMECmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isQueued\n"
;
  }

  static const char* value(const ::dobot::SetHOMECmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isQueued);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHOMECmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::SetHOMECmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::SetHOMECmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "isQueued: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isQueued);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_SETHOMECMDREQUEST_H
