// Generated by gencpp from file dobot/SetQueuedCmdForceStopExecResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETQUEUEDCMDFORCESTOPEXECRESPONSE_H
#define DOBOT_MESSAGE_SETQUEUEDCMDFORCESTOPEXECRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct SetQueuedCmdForceStopExecResponse_
{
  typedef SetQueuedCmdForceStopExecResponse_<ContainerAllocator> Type;

  SetQueuedCmdForceStopExecResponse_()
    : result(0)  {
    }
  SetQueuedCmdForceStopExecResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetQueuedCmdForceStopExecResponse_

typedef ::dobot::SetQueuedCmdForceStopExecResponse_<std::allocator<void> > SetQueuedCmdForceStopExecResponse;

typedef boost::shared_ptr< ::dobot::SetQueuedCmdForceStopExecResponse > SetQueuedCmdForceStopExecResponsePtr;
typedef boost::shared_ptr< ::dobot::SetQueuedCmdForceStopExecResponse const> SetQueuedCmdForceStopExecResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator1> & lhs, const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator1> & lhs, const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/SetQueuedCmdForceStopExecResponse";
  }

  static const char* value(const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
;
  }

  static const char* value(const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetQueuedCmdForceStopExecResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::SetQueuedCmdForceStopExecResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_SETQUEUEDCMDFORCESTOPEXECRESPONSE_H
